export const MODE = process.env.NEXT_PUBLIC_NODE_ENV || "development";

export const HOST_PORT = process.env.NEXT_PUBLIC_HOST_PORT || 1995;
export const HOST_URL = process.env.NEXT_PUBLIC_HOST_URL;
export const CLIENT_PORT = process.env.NEXT_PUBLIC_CLIENT_PORT || 1997;
export const CLIENT_URL = process.env.NEXT_PUBLIC_CLIENT_URL;

export const HOST_VERSION = process.env.NEXT_PUBLIC_HOST_VERSION;

export const HOST_API_URL = `${HOST_URL}/api/${HOST_VERSION}`;

export const GOOGLE_OAUTH_CLIENT_ID =
  process.env.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID;
export const GOOGLE_OAUTH_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_SECRET;

export const GITHUB_OAUTH_CLIENT_ID =
  process.env.NEXT_PUBLIC_GITHUB_OAUTH_CLIENT_ID;
export const GITHUB_OAUTH_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_GITHUB_OAUTH_CLIENT_SECRET;

export const FACEBOOK_OAUTH_CLIENT_ID =
  process.env.NEXT_PUBLIC_FACEBOOK_OAUTH_CLIENT_ID;
export const FACEBOOK_OAUTH_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_FACEBOOK_OAUTH_CLIENT_SECRET;

export const LINKEDIN_OAUTH_CLIENT_ID =
  process.env.NEXT_PUBLIC_LINKEDIN_OAUTH_CLIENT_ID;
export const LINKEDIN_OAUTH_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_LINKEDIN_OAUTH_CLIENT_SECRET;
