import { PERMISSIONS } from "../constants/permission.constants.js";
import { ROLES } from "../constants/roles.constants.js";

export const ROLE_PERMISSIONS_MAP = {
  [ROLES.SUPER_ADMIN]: [PERMISSIONS.ALL],

  [ROLES.ADMIN]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ_OWN,
    PERMISSIONS.USER_READ_ANY,
    PERMISSIONS.USER_UPDATE_ANY,
    PERMISSIONS.USER_DELETE_OWN,
    PERMISSIONS.USER_DELETE_ANY,
    PERMISSIONS.USER_LIST,
    PERMISSIONS.USER_SUSPEND_OWN,
    PERMISSIONS.USER_SUSPEND_ANY,

    PERMISSIONS.PROFILE_READ_OWN,
    PERMISSIONS.PROFILE_READ_ANY,
    PERMISSIONS.PROFILE_UPDATE_OWN,
    PERMISSIONS.PROFILE_UPDATE_ANY,

    PERMISSIONS.ADDRESS_CREATE_OWN,
    PERMISSIONS.ADDRESS_CREATE_ANY,
    PERMISSIONS.ADDRESS_READ_OWN,
    PERMISSIONS.ADDRESS_READ_ANY,
    PERMISSIONS.ADDRESS_UPDATE_OWN,
    PERMISSIONS.ADDRESS_UPDATE_ANY,
    PERMISSIONS.ADDRESS_DELETE_OWN,
    PERMISSIONS.ADDRESS_DELETE_ANY,

    PERMISSIONS.SESSION_READ_OWN,
    PERMISSIONS.SESSION_READ_ANY,
    PERMISSIONS.SESSION_DELETE_ANY,
    PERMISSIONS.SESSION_REVOKE_OWN,
    PERMISSIONS.SESSION_REVOKE_ANY,

    PERMISSIONS.ACTIVITY_READ_OWN,
    PERMISSIONS.ACTIVITY_READ_ANY,
    PERMISSIONS.ACTIVITY_RESET_OWN,
    PERMISSIONS.ACTIVITY_RESET_ANY,

    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT_OWN,
    PERMISSIONS.AUTH_LOGOUT_ANY,
    PERMISSIONS.AUTH_REFRESH,

    PERMISSIONS.ROLE_CREATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_UPDATE,
    PERMISSIONS.ROLE_DELETE,
    PERMISSIONS.ROLE_ASSIGN,

    PERMISSIONS.PERMISSION_CREATE,
    PERMISSIONS.PERMISSION_READ,
    PERMISSIONS.PERMISSION_UPDATE,
    PERMISSIONS.PERMISSION_DELETE,

    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.ADMIN_AUDIT_LOG_READ,

    PERMISSIONS.SYSTEM_CONFIG_UPDATE,
  ],

  [ROLES.USER]: [
    PERMISSIONS.USER_READ_OWN,
    PERMISSIONS.USER_UPDATE_OWN,
    PERMISSIONS.USER_SUSPEND_OWN,
    PERMISSIONS.USER_DELETE_OWN,

    PERMISSIONS.PROFILE_READ_OWN,
    PERMISSIONS.PROFILE_READ_ANY,
    PERMISSIONS.PROFILE_UPDATE_OWN,

    PERMISSIONS.ADDRESS_CREATE_OWN,
    PERMISSIONS.ADDRESS_READ_OWN,
    PERMISSIONS.ADDRESS_UPDATE_OWN,
    PERMISSIONS.ADDRESS_DELETE_OWN,

    PERMISSIONS.SESSION_READ_OWN,
    PERMISSIONS.SESSION_REVOKE_OWN,

    PERMISSIONS.ACTIVITY_READ_OWN,
    PERMISSIONS.ACTIVITY_RESET_OWN,

    PERMISSIONS.AUTH_LOGOUT_OWN,
    PERMISSIONS.AUTH_REFRESH,
  ],
};
